name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_NUMBER: ${{ GITHUB.RUN_NUMBER }}
        run: mvn --settings settings.xml -batch-mode deploy
          
